# Generated by Django 4.1.2 on 2022-10-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_alter_credit_dni_alter_credit_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='credit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='dni',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='productos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
